### ISSUE TITLE
Use "terminology" ISO-639 codes

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/wikipron#406]
Currently we are using the ISO-639-2 "bibliographic" codes ("ger" for German). It seems to me that these are not terribly widely used and make compatibility with other multilingual resources poorer than they'd be otherwise; i.e., one has to convert, as I did for #393. I would suggest instead that we switch to the more widely used ISO-639-3 codes, which are "terminological" ("deu" for German). This should be relatively straightforward.

Any thoughts @lfashby @ajmalanoski @agutkin @jacksonllee?

**Comment by agutkin** [comment]
The bibliographic codes would be ISO-639-2/B, right?

I think migrating to ISO-639-3 makes sense.

**Comment by kylebgorman** [comment]
Yeah @agutkin. For whatever reason that's what our ISO code library spits out. Haven't looked into it further.

**Comment by agutkin** [comment]
Ha, interesting:

>   […] the German language (Part 1: `de`) has two codes in Part 2: `ger` (T code) and `deu` (B code), 
>   whereas there is only one code in Part 2, `eng`, for the English language.

So I guess the ISO library does the right thing returning the terminologic Part 2 code for German, rather than bibliographic.

**Comment by jacksonllee** [comment]
+1 for switching to / using ISO 639-3 codes consistently. I'd imagine German speakers would prefer seeing `deu` rather than `ger`, `fra` for French rather than `fre`, etc.

**Comment by ajmalanoski** [comment]
+1 for switching to the more widely used format

**Comment by jacksonllee** [comment]
For other projects I also need ISO 639 language code look-up in Python, and so I've just released my own package for this purpose and planned on keeping the language codes in there up-to-date moving forward: https://github.com/jacksonllee/iso639

(Other similar Python packages, like the one we've been using in WikiPron, have been unmaintained for 6+ years. There's also pycountry, but it's not as lightweight as we'd want since it has all the other stuff apart from ISO 639 language codes.)

Happy to review a PR that resolves this ticket, however it's gonna be done. It looks like we should be able to simplify things in the repo quite a bit:
* Remove [iso639_1-to-iso639_2.json](https://github.com/CUNY-CL/wikipron/blob/206a2c1b323231421eaa68853bbf86915de96668/data/scrape/lib/iso639_1-to-iso639_2.json), [iso69_2.json](https://github.com/CUNY-CL/wikipron/blob/206a2c1b323231421eaa68853bbf86915de96668/data/scrape/lib/iso639_2.json), and [unimorph_languages.json](https://github.com/CUNY-CL/wikipron/blob/206a2c1b323231421eaa68853bbf86915de96668/data/morphology/unimorph_languages.json).
* Simplify [languagecodes.py](https://github.com/CUNY-CL/wikipron/blob/206a2c1b323231421eaa68853bbf86915de96668/wikipron/languagecodes.py), e.g., by removing the entries with the comment `ISO 639-3 only`.

**Comment by jacksonllee** [comment]
> Is it on PyPI yet?

Yes -- https://pypi.org/project/python-iso639/
