### ISSUE TITLE
Enhancement suggestions for building personal corpora

### ISSUE THREAD

**Issue by warnak** [CUNY-CL/wikipron#439]
Hello! I wanted to suggest and work on a few quick enhancements as listed below:

1. Pulling user specified number of entries.
2. Randomizing entries if needed.
3. Ability to select what part (for example `f` to `s` for English or `ग` to `ब` for Hindi etc.) to pull.
4. Multi-language pulls (to be able to pull English and Hindi in one go)

Please let me know if I can work on any of these or if you have any similar suggestions I could work on!

**Comment by jacksonllee** [comment]
Hello, to facilitate building personal corpora, this repo provides the scraped TSVs from Wiktionary (in [this directory](https://github.com/CUNY-CL/wikipron/tree/master/data/scrape/tsv), where you'll find both English and Hindi datasets) and updates them with the latest upstream data on a regular cadence. Rather than being part of the core `wikipron` Python package, the use cases you've listed could be implemented as a post-processing step in your own personal pipeline on top of these scraped TSVs.

**Comment by warnak** [comment]
Hello @jacksonllee and thanks! I will close this issue then, sorry for any inconvenience.
