### ISSUE TITLE
[pam] Can't parse both types of transcriptions from the same line?

### ISSUE THREAD

**Issue by agutkin** [CUNY-CL/wikipron#478]
For [Kapampangan](https://en.wiktionary.org/wiki/Category:Kapampangan_terms_with_IPA_pronunciation)(`pam`) the format of all pronunciation entries looks as [follows](https://en.wiktionary.org/wiki/batiauan#Kapampangan):

```
Hyphenation: ba‧tia‧uan
IPA(key): /bəˈtjawən/, [bəˈtjäː.wən]
```

I suspect we can't parse this when both transcriptions are under the same heading. May be a duplicate.

**Comment by agutkin** [comment]
After configuring and adding the language, the respective scrape comes out as empty.

**Comment by kylebgorman** [comment]
I don't see the problem from your description. This is exactly what, say, Spanish looks like: `<span class="IPA">` with `[.*]` or `/.*/`.

**Comment by agutkin** [comment]
Here we have `<span class="IPA"> with [.*] and /.*/.

**Comment by kylebgorman** [comment]
Then I don't know why it's not working.

**Comment by sonofthomp** [comment]
This issue actually has nothing to do with there being two IPAs on the same line.

The HTML of the page for "batiauan" contains the following:
```html
<li>
    <a href="/wiki/Wiktionary:International_Phonetic_Alphabet" title="Wiktionary:International Phonetic Alphabet">IPA</a>
    <sup>
         (<a href="https://en.wikipedia.org/wiki/Kapampangan_phonology"
             class="extiw"
             title="wikipedia:Kapampangan phonology">key</a>)
    </sup>
    : 
    <span class="IPA">/bəˈtjawən/</span>
    , 
    <span class="IPA">[bəˈtjäː.wən]</span>
</li>
```

The XPATH trying to match it is:
```html
(//li|//p)[
  (.|span)[sup[a[
    @title = "Appendix:Pampanga pronunciation"
    or
    @title = "wikipedia:Pampanga phonology"
  ]]]
  and
  span[@class = "IPA"]
  
]
```

The problem is that the XPATH is trying to find an element with `wikipedia:Pampanga phonology` as its title when the 
element it's looking for has `wikipedia:Kapampangan phonology` as its title.

The reason for this is that Wikipron incorrectly thinks that the correct name of the language `pam` is "Pampanga". When you run the command `wikipron pam`, the function [`_get_language()`](https://github.com/CUNY-CL/wikipron/blob/c0fa3e0fe64592996fd92c49a88954f481f624e2/wikipron/config.py#L88-L104) tries to find the name of the language associated with the code `pam`. Because `pam` isn't listed in languagecodes.py, the function uses the iso639 library to try to find the name associated with `pam` and comes up with Pampanga instead of Kampampangan. This then gets passed into the [XPATH template in config.py](https://github.com/CUNY-CL/wikipron/blob/c0fa3e0fe64592996fd92c49a88954f481f624e2/wikipron/config.py#L19-L30), which then gets used to parse the HTML.

I think the best solution would be to fix `_get_language()` so that it gets the correct language (the one Wiktionary actually uses). We already have a mapping of every language code to its name on Wikipron in [languages.json](https://github.com/CUNY-CL/wikipron/blob/c0fa3e0fe64592996fd92c49a88954f481f624e2/data/scrape/lib/languages.json#L1093-L1098) -- why not just use that instead of querying language_codes.py and the iso639 library?

**Comment by kylebgorman** [comment]
So good question. `languages.json` has metadata specific to the big scrape; it's not used when one uses the command-line tool nor is it shipped in the `wikipron` package.

It seems like we need to just update `languagecodes.py` to include the mappign `"pam": "Kapampangan"`, right?

**Comment by sonofthomp** [comment]
> It seems like we need to just update languagecodes.py to include the mappign "pam": "Kapampangan", right?

Okay, that seems reasonable. I also found [76 examples other](https://pastebin.com/4hHiLEs5) than `pam` that have the same discrepancy between iso639 name and Wiktionary name. They have the same problem with their XPATH having the wrong `title` attribute. I'll update those as well if that makes sense to you.

**Comment by kylebgorman** [comment]
Nice, yes that sounds good. At least some of the examples there are already in the file, FYI.

**Comment by sonofthomp** [comment]
Made a PR
